---
abstract: 'Dist::Zilla plugin defaults for Companies House'
author:
  - 'Companies House <chgovuk@cpan.org>'
build_requires:
  Module::Build: '0.3601'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-CHGOVUK
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dist::Zilla::Plugin::CheckChangesHasContent: '0'
  Dist::Zilla::Plugin::CopyFilesFromBuild: '0'
  Dist::Zilla::Plugin::CopyFilesFromRelease: '0'
  Dist::Zilla::Plugin::Git::CommitBuild: '0'
  Dist::Zilla::Plugin::Git::GatherDir: '0'
  Dist::Zilla::Plugin::GithubMeta: '0'
  Dist::Zilla::Plugin::NameFromDirectory: '0'
  Dist::Zilla::Plugin::Prereqs::FromCPANfile: '0'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0'
  Dist::Zilla::Plugin::ReadmeFromPod: '0'
  Dist::Zilla::Plugin::VersionFromModule: '0'
  Test::Pod: '0'
resources:
  bugtracker: https://github.com/companieshouse/Dist-Zilla-PluginBundle-CHGOVUK/issues
  homepage: https://github.com/companieshouse/Dist-Zilla-PluginBundle-CHGOVUK
  repository: https://github.com/companieshouse/Dist-Zilla-PluginBundle-CHGOVUK.git
version: '0.07'
